src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import Login

urlpatterns = [
    path('', Login.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

src/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.Index.as_view(), name="list"),
    path("detail/<int:pk>/", views.PostDetail.as_view(), name="detail"),
    path("detail/<int:pk>/edit/", views.PostUpdate.as_view(), name="edit"),
    path("detail/<int:pk>/delete/", views.PostDelete.as_view(), name="delete"),
    path("detail/<int:pk>/comment/write/", views.CommentWrite.as_view(), name="cm-write"),
    path("detail/comment/<int:pk>/delete/", views.CommentDelete.as_view(), name="cm-delete"),
    path("search/", views.Search.as_view(), name="search"),
    path("tag-search/", views.TagSearch.as_view(), name="tag-search"),
    path("write/", views.PostWrite.as_view(), name="write"),
]

src/user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("signup/", views.Signup.as_view(), name="signup"),
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
]

src/templates/base.html
{% load static %}
{% load base64_to_img %}
{% load find_img %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="HTML5 Template"/>
    <meta name="description" content="Webster - Responsive Multi-purpose HTML5 Template"/>
    <meta name="author" content="potenzaglobalsolutions.com"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <title>
      {% block title %}{% endblock %}
    </title>

    <!-- font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,500,500i,600,700,800,900|Poppins:200,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900">

    <!-- Plugins -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/plugins-css.css' %}"/>

    <!-- Typography -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/typography.css' %}"/>

    <!-- Shortcodes -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/shortcodes/shortcodes.css' %}"/>

    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>

    <!-- Responsive -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}"/>

    <style>
      .page-title {
        padding-top: 200px;
        padding-bottom: 50px;
      }
    </style>
    {% block extra_css %}{% endblock %}
    {% block extra_head %}{% endblock %}
  </head>

  <body>
    <div class="wrapper">

      <!--================================= preloader -->

      <div id="pre-loader">
        <img src="{% static 'images/pre-loader/loader-01.svg' %}" alt="">
      </div>

      <!--================================= preloader -->

      <!--================================= header -->
      {% block menu %}
        <header id="header" class="header default">
          <div class="topbar">
            <div class="container">
              <div class="row">
                <div class="col-lg-6 col-md-6 xs-mb-10">
                  <div class="topbar-call text-center text-md-start">
                    <ul>
                      <li>
                        <i class="fa fa-envelope-o theme-color"></i>
                        inslog94@gmail.com</li>
                    </ul>
                  </div>
                </div>
                <div class="col-lg-6 col-md-6">
                  <div class="topbar-social text-center text-md-end">
                    <ul>
                      <li>
                        <a href="#">
                          <span class="ti-facebook"></span></a>
                      </li>
                      <li>
                        <a href="#">
                          <span class="ti-instagram"></span></a>
                      </li>
                      <li>
                        <a href="#">
                          <span class="fa fa-google"></span></a>
                      </li>
                      <li>
                        <a href="#">
                          <span class="ti-twitter"></span></a>
                      </li>
                      <li>
                        <a href="#">
                          <span class="ti-linkedin"></span></a>
                      </li>
                      <li>
                        <a href="#">
                          <span class="ti-dribbble"></span></a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--================================= mega menu -->
          <div class="menu">
            <!-- menu start -->
            <nav id="menu" class="mega-menu">
              <!-- menu list items container -->
              <section class="menu-list-items">
                <div class="container">
                  <div class="row">
                    <div class="col-lg-12 col-md-12 position-relative">
                      <!-- menu logo -->
                      <ul class="menu-logo">
                        <li>
                          <h1>
                            <a href="{% url 'blog:list' %}" class="text-white">
                              BLOG
                              <img src="" alt="">
                            </a>
                          </h1>
                        </li>
                      </ul>
                      <!-- menu links -->
                      <div class="menu-bar">
                        <ul class="menu-links">
                          <li>
                            <a href="{% url 'index' %}">Home</a>
                          </li>
                          {% if not request.user.is_authenticated %}
                            <li>
                              <a href="{% url 'user:login' %}">Login</a>
                            </li>
                            <li>
                              <a href="{% url 'user:signup' %}">Signup</a>
                            </li>
                          {% else %}
                            <li>
                              <a href="{% url 'user:logout' %}">logout</a>
                            </li>
                          {% endif %}
                        </ul>
                        <div class="search-cart">
                          <div class="search">
                            <a class="search-btn not_click" href="javascript:void(0);"></a>
                            <div class="search-box not-click">
                              <form action="/blog/search/" method="get">
                                <input type="text" class="not-click form-control" name="name" placeholder="Search.." value="">
                                <button class="search-button" type="submit">
                                  <i class="fa fa-search not-click"></i>
                                </button>
                              </form>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </nav>
          <!-- menu end -->
        </div>
      </header>

      <!--================================= header -->

      <!--================================= page-title-->

      <section class="page-title bg-overlay-black-60 jarallax" data-speed="0.6" data-img-src="">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="page-title-name">
                <h2 class="fs-25 text-white">
                  {% block sub-title %}{% endblock %}
                </h2>
              </div>
              <ul class="page-breadcrumb">
                <li>
                  <a href="#">
                    <i class="fa fa-home"></i>
                    Root</a>
                  <i class="fa fa-angle-double-right"></i>
                </li>
                <li>
                  <a href="#">
                    {% block root_b %}{% endblock %}
                  </a>
                  <i class="fa fa-angle-double-right"></i>
                </li>
                <li>
                  <a href="#">
                    {% block root_c %}{% endblock %}
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
    {% endblock %}
    <!--================================= page-title -->

    {% block content %}{% endblock %}

    <!--================================= footer -->

    <footer class="footer pt-10 black-bg fixed-bottom">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-6">
            <p class="mt-15">
              &copy;Copyright
              <span id="copyright">
                <script>
                  document
                    .getElementById('copyright')
                    .appendChild(document.createTextNode(new Date().getFullYear()))
                </script>
              </span>
              <a href="#">
                Inslog94
              </a>
              All Rights Reserved
            </p>
          </div>
          <div class="col-lg-6 col-md-6 text-start text-md-end">
            <div class="social-icons color-hover mt-10">
              <ul>
                <li class="social-facebook">
                  <a href="#">
                    <i class="fa fa-facebook"></i>
                  </a>
                </li>
                <li class="social-linkedin">
                  <a href="#">
                    <i class="fa fa-linkedin"></i>
                  </a>
                </li>
                <li class="social-dribbble">
                  <a href="#">
                    <i class="fa fa-dribbble"></i>
                  </a>
                </li>
                <li class="social-twitter">
                  <a href="#">
                    <i class="fa fa-twitter"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <!--================================= footer -->

</div>

<div id="back-to-top">
  <a class="top arrow" href="#top">
    <i class="fa fa-angle-up"></i>
    <span>TOP</span></a>
</div>

<!--================================= jquery -->

<!-- jquery -->
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

<!-- plugins-jquery -->
<script src="{% static 'js/plugins-jquery.js' %}"></script>

<!-- plugin_path -->
<script>
  const plugin_path = "{% static 'js/' %}";
</script>

<!-- custom -->
<script src="{% static 'js/custom.js' %}"></script>

{% block extra_js %}{% endblock %}
</body>

</html>