src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import Login

urlpatterns = [
    path('', Login.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

src/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.Index.as_view(), name="list"),
    path("detail/<int:pk>/", views.PostDetail.as_view(), name="detail"),
    path("detail/<int:pk>/edit/", views.PostUpdate.as_view(), name="edit"),
    path("detail/<int:pk>/delete/", views.PostDelete.as_view(), name="delete"),
    path("detail/<int:pk>/comment/write/", views.CommentWrite.as_view(), name="cm-write"),
    path("detail/comment/<int:pk>/delete/", views.CommentDelete.as_view(), name="cm-delete"),
    path("search/", views.Search.as_view(), name="search"),
    path("tag-search/", views.TagSearch.as_view(), name="tag-search"),
    path("write/", views.PostWrite.as_view(), name="write"),
]

src/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)
    tags = models.ManyToManyField('Tag')
    
    def __str__(self):
        return self.title

    
class Tag(models.Model):
    content = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return self.content
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.content

src/blog/forms.py
from django import forms
from .models import Post, Tag, Comment


class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'content']
        widgets = {
            'title': forms.TextInput(attrs={"placeholder": "제목을 입력해주세요.", "class": "form-control mt-40 mb-20"}),
            'content': forms.Textarea(attrs={'id': 'content'})
        }


class TagForm(forms.ModelForm):
    
    class Meta:
        model = Tag
        fields = ['content']


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.TextInput(attrs={"placeholder": "댓글을 입력해주세요.", "class": "comment-input form-control"})
        }

src/blog/views.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Tag, Comment
from .forms import PostForm, TagForm, CommentForm


class Index(View):
    def get(self, req):
        posts = Post.objects.all().order_by('-pk')
        tags = Tag.objects.all()
        comments = Comment.objects.all().order_by('-pk')
        context = {
            "posts": posts,
            "tags": tags,
            "comments": comments[:3],
        }
        
        return render(req, "blog/post_list.html", context)
    

class PostDetail(View):
    def get(self, req, pk):
        # post = Post.objects.get(pk=pk)
        # print(post)
        post = get_object_or_404(Post, pk=pk)
        print(post)
        
        if post.is_deleted:
            return render(req, "blog/post_deleted.html")
        
        # comments = Comment.objects.select_related('post').filter(post=post)
        comments = post.comment_set.all()
        print('comments', comments)
        
        comment_form = CommentForm()
        
        # tags = Tag.objects.select_related('post').filter(post__pk=pk)
        tags = post.tags.all()
        print("tags", tags)
        context = {
            "post": post,
            "tags": tags,
            "comments": comments,
            "comment_form": comment_form,
        }
        
        return render(req, "blog/post_detail.html", context)


class Search(View):
    def get(self, req):
        query = req.GET.get('name')
        print(query)
        posts = Post.objects.filter(title__contains=query)
        print(posts)
        context = {
            "query": query,
            "posts": posts
        }
        
        return render(req, 'blog/post_search.html', context)
    

class TagSearch(View):
    def get(self, req):
        query = req.GET.get('name')
        print(query)
        tag = Tag.objects.get(content=query)
        posts = tag.post_set.all()
        print(posts)
        context = {
            "query": query,
            "posts": posts
        }
        
        return render(req, 'blog/post_search.html', context)

    
class PostDelete(LoginRequiredMixin, View):
    def post(self, req, pk):
        post = Post.objects.get(pk=pk)
        print("delete", post)
        post.is_deleted = True
        post.save()
        
        return redirect('blog:list')
    
    
class PostWrite(LoginRequiredMixin, View):
    def get(self, req):
        form = PostForm()
        tagForm = TagForm()
        context = {
            'form': form,
            'tagForm': tagForm
        }
        
        return render(req, "blog/post_form.html", context)
    
    def post(self, req):
        post_form_data = {
            "title": req.POST.get("title"),
            "content": req.POST.get("content"),
        }
        
        form = PostForm(data=post_form_data)
        
        tag_form_data = {
            "content": req.POST.get("tags")
        }
        
        tag_form = TagForm(data=tag_form_data)
        if form.is_valid() and tag_form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            writer = req.user
            post = Post(title=title, content=content, writer=writer)
            post.save()
            
            form_content = tag_form.cleaned_data['content']
            tags = []
            if form_content:
                form_content = form_content.split(",")
                if tag_form:
                    print(form_content)
                    for i in form_content:
                        tag, created = Tag.objects.get_or_create(content=i)
                        tags.append(tag)
            post.tags.set(tags)
        
            return redirect('blog:list')


class PostUpdate(LoginRequiredMixin, View):
    def get(self, req, pk):
        post = Post.objects.get(pk=pk)
        form = PostForm(initial={'title': post.title, 'content': post.content})
        tags = post.tags.all()
        context = {
            'content': post.content,
            'form': form,
            'post': post,
            'tags': tags,
        }
        
        return render(req, 'blog/post_edit.html', context)
    
    def post(self, req, pk):
        post = Post.objects.get(pk=pk)
        post_form_data = {
            "title": req.POST.get("title"),
            "content": req.POST.get("content"),
        }
        
        form = PostForm(data=post_form_data)
        
        tag_form_data = {
            "content": req.POST.get("tags")
        }
        
        print(req.POST.get("tags"))
        tag_form = TagForm(data=tag_form_data)
        if form.is_valid() and tag_form.is_valid():
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.save()
            
            form_content = tag_form.cleaned_data['content']
            tags = []
            post.tags.all().delete()
            if form_content:
                form_content = form_content.split(",")
                if tag_form:
                    print("clean", form_content)
                    for i in form_content:
                        tag, created = Tag.objects.get_or_create(content=i)
                        tags.append(tag)
            post.tags.set(tags)
        
            return redirect('blog:list')


class CommentWrite(View):
    def post(self, req, pk):
        post = Post.objects.get(pk=pk)
        form = CommentForm(req.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            writer = req.user
            print("댓글 작성자", writer)

            if not req.user.is_authenticated:
                print("익명입니다")
                comment = Comment.objects.create(post=post, content=content, writer=None)
            else:
                comment = Comment.objects.create(post=post, content=content, writer=writer)

            return redirect('blog:detail', pk=pk)


class CommentDelete(View):
    def post(self, req, pk):
        comment = Comment.objects.get(pk=pk)
        post_id = comment.post.id
        comment.delete()
        
        return redirect('blog:detail', pk=post_id)

src/blog/templates/blog/post_deleted.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Blog - Edit{% endblock %}
{% block extra_css %}{% endblock %}

{% block sub-title %}Deleted Post{% endblock %}
{% block root_b %}Blog{% endblock %}
{% block root_c %}Not Found{% endblock %}

{% block content %}
  <div class="container">
    <div class="d-flex board justify-content-center mt-100">
      <h3>존재하지 않는 게시글입니다</h3>
    </div>
  </div>
{% endblock %}

src/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load base64_to_img %}

{% block title %}Blog - Detail{% endblock %}
{% block extra_css %}
  <style>
    .post-img {
      max-width: 100%;
    }

    .post-img img {
      max-width: 100%;
    }

    .post-edit-delete {
      width: 100px;
    }

    .addCommentBtn {
      height: 100%;
      width: 75px;
    }

    .deleteCommentBtn {
      height: 90%;
    }
  </style>
{% endblock %}

<!--================================= page-title-->

{% block sub-title %}Blog Detail{% endblock %}
{% block root_b %}Blog{% endblock %}
{% block root_c %}Detail{% endblock %}

<!--================================= page-title -->

{% block content %}

  <!--================================= single-portfolio-post-->

  <section class="single-portfolio-post white-bg page-section-ptb">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 port-information">
          <div class="port-title sm-mt-40">
            <h3 class="mb-30">{{ post.title }}</h3>
            {% if post.writer == request.user %}
              <form action="{% url 'blog:delete' pk=post.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" class="button button-border border-danger float-end bg-danger post-edit-delete ml-10" value="delete">
              </form>
              <a href="{% url 'blog:edit' pk=post.pk %}" class="button button-border border-info float-end bg-info post-edit-delete">
                edit
              </a>
            {% endif %}
          </div>
          <div class="port-meta clearfix">
            <ul class="list-unstyled">
              <li>
                <b>Writer:</b>
                <span>{{ post.writer }}</span></li>
              <li>
                <b>Date:
                </b>
                <span>{{ post.created_at }}</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!--=================================-->
      <div class="row">
        <div class="col-lg-12">
          <div class="port-info mt-50 mb-50">
            <p>{{ post.content|base64_to_image }}</p>
          </div>
        </div>
      </div>
      <div class="d-flex align-items-center justify-content-between mb-30">
        <div class="tags">
          <h5>Tags:</h5>
          <ul>
            {% if tags %}
              {% for tag in tags %}
                <li>
                  <a href="" class='tagSearch'>
                    {{ tag }}
                  </a>
                </li>
              {% endfor %}
            {% endif %}
          </ul>
        </div>
        <div class="share">
          <div class="social">
            <strong>Share :</strong>
            <ul>
              <li>
                <a href="#">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-pinterest-p"></i>
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-dribbble"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!--=================================-->
      <div class="row">
        <div class="col-lg-12">
          <div class="port-navigation clearfix">
            <form action="{% url 'blog:cm-write' pk=post.pk %}" method="post">
              {% csrf_token %}
              <h6 class="mt-30 mb-20">Comment Write
              </h6>
              <div class="d-flex">
                {{ comment_form.content }}
                <input type="submit" class="button addCommentBtn col-1" value="등록"></input>
              </div>
            </form>
          </div>
          {% for comment in comments %}
            <div class="d-flex align-items-center justify-content-between mt-3">
              <span>{{ comment.content }}
                -
                {{ comment.writer }}
                -
                {{ comment.created_at }}</span>
              {% if comment.writer == request.user %}
                <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                  {% csrf_token %}
                  <input type="submit" class="deleteCommentBtn" value="x">
                </form>
              {% endif %}
            </div>

          {% endfor %}
        </div>
      </div>
    </div>
  </section>

{% endblock %}

{% block extra_js %}
  <script>
    $tags = document.querySelectorAll('.tagSearch');
    $tags.forEach((tag) => {
      tag.addEventListener('click', (event) => tagSearch(event, tag));
    });

    function tagSearch(event, tag) {
      event.preventDefault()
      const url = "{% url 'blog:tag-search' %}?name=" + tag
        .textContent
        .trim()
      window.location.href = url;
    }
  </script>
{% endblock %}

src/blog/templates/blog/post_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Blog - Edit{% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css"/>
<script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
<style>
  .addTagBtn {
    width: 75px
  }

  #tagList {
    list-style: none;

  .tagDelete {
    height: 100%;
    border: none;
    background: inherit;
  }

  .tag{
    display: inline-block;
    padding: 5px;
  }
  }
</style>
{% endblock %}

<!--================================= page-title-->

{% block sub-title %}Blog Edit{% endblock %}
{% block root_b %}Blog{% endblock %}
{% block root_c %}Edit{% endblock %}


{% block content %}
<div class="container">
  <form action="{% url 'blog:edit' pk=post.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" class="button col-1 float-end mt-20 mb-20" value="수정">
    <div>
      <!-- <label for="{{ form.title.id_for_label }}">Title:</label> -->
      {{ form.title }}
    </div>
    <div>
      <!-- <label for="{{ form.content.id_for_label }}">Content:</label> -->
      <div id="content"></div>
    </div>
    <input type="hidden" name="{{ form.content.html_name }}" id="{{ form.content.auto_id }}" value="{{ form.content.value }}">
    <div>
      {% comment %} {{ tagForm.content }} {% endcomment %}
      <h6 class="mt-30 mb-20">Tag Write
      </h6>
      <div class="d-flex">
        <input type="text" class="form-control tagInput" placeholder="태그를 입력해주세요.">
        <button type="button" class="button addTagBtn col-1">추가</button>
    </div>
    <div class="d-flex align-items-center justify-content-between mb-30">
      <div class="tags mt-10 mb-10">
        <ul id="tagList">
        </ul>
      </div>
    </div>
  </div>
  <input type="hidden" name="tags" id="tagsInput" value="">
  </form>
</div>
{% endblock %}
{% block extra_js %}
<script>
  const Editor = toastui.Editor;
  const editor = new Editor({
    el: document.querySelector('#content'),
    height: '500px',
    initialEditType: 'wysiwyg',
    previewStyle: 'vertical',
    events: {
      change: function () {
        const value = editor.getHTML();
        document
          .querySelector("#{{ form.content.auto_id }}")
          .value = value;
      }
    }
  });

  $quoteBtn = document.querySelector('.quote');
  $quoteBtn.parentNode.removeChild($quoteBtn);

  const initialContent = "{{ content|escapejs }}";
  editor.setMarkdown(initialContent);

  const tagInput = document.querySelector('.tagInput');
  const addTagBtn = document.querySelector('.addTagBtn');
  const tagList = document.querySelector('#tagList');
  const tagsInput = document.querySelector('#tagsInput');
  const tags = [];

  const initialTags = ("{{ tags|escapejs }}".replace('QuerySet ', '').replaceAll(/<|>|Tag: |/g, '')).slice(1, -1).split(', ')
  initialTags.forEach((initialTag) => addTag(initialTag))

  tagInput.addEventListener('keydown', enterHandler)
  addTagBtn.addEventListener('click', addTag);

  function enterHandler(event) {
    if (event.keyCode === 13) {
      event.preventDefault();
      addTag()
    }
  }

  function addTag(initialTag=null) {
    let tag = null
    if (initialTag !== null) {
      tag = initialTag
      } else {
      tag = tagInput
        .value
        .trim();
      }

    if (tag) {
      tags.push(tag);

      const anchor = document.createElement('a');
      anchor.classList.add('tag');
      const listItem = document.createElement('li');
      const deleteBtn = document.createElement('button');
      deleteBtn.classList.add('tagDelete', 'button-border');
      deleteBtn.textContent = 'x';

      deleteBtn.addEventListener('click', () => {
        const index = tags.indexOf(tag);
        if (index > -1) {
          tags.splice(index, 1);
        }
        tagList.removeChild(listItem);
        updateTagsInputValue();
      });

      anchor.textContent = tag;
      anchor.appendChild(deleteBtn)
      listItem.appendChild(anchor);
      tagList.appendChild(listItem);
      tagInput.value = '';

      updateTagsInputValue();
    }
  }

  function updateTagsInputValue() {
    tagsInput.value = tags.join(',');
  }
  // editor.getHTML()
  // editor.getMarkdown()
</script>
{% endblock %}

src/blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load base64_to_img %}
{% load find_img %}

{% block title %}Blog - List{% endblock %}
{% block extra_css %}
  <style>
    .write {
      width: 100%;
    }
  </style>
{% endblock %}

<!--================================= page-title-->

{% block sub-title %}Blog Timeline{% endblock %}
{% block root_b %}Blog{% endblock %}
{% block root_c %}List{% endblock %}

<!--================================= page-title -->

{% block content %}

  <!--================================= blog timeline sidebar-->

  <section class="white-bg blog timeline-sidebar page-section-ptb">
    <div class="container mb-50">
      <div class="row">
        <div class="col-lg-9">
          {% if posts %}
            <ul class="timeline">
              <li class="entry-date">
                <span>
                  {{ posts.last.created_at|date:"F Y" }}
                </span>
              </li>
              <!--================================= post with images -->
              {% for post in posts %}
                {% if not post.is_deleted %}
                  {% if "(data:image" in post.content %}
                    <li class="timeline-inverted">
                      <div class="timeline-badge primary">
                        <a href="#">{{ post.created_at|date:"d" }}
                          <span>{{ post.created_at|date:"M" }}</span></a>
                      </div>
                      <div class="timeline-panel">
                        <div class="blog-entry">
                          <div class="entry-image clearfix">
                            {{ post.content|get_first_image_tag }}
                          </div>
                          <div class="blog-detail">
                            <div class="entry-title mb-10">
                              <a href="{% url 'blog:detail' pk=post.pk %}">{{ post.title }}</a>
                            </div>
                            <div class="entry-meta mb-10">
                              <ul>
                                <li>
                                  <i class="fa fa-hashtag"></i>
                                  {% if post.tags.all %}
                                    {% for tag in post.tags.all %}
                                      <li>
                                        <a href="" class='tagSearch'>
                                          {{ tag }}
                                        </a>
                                      </li>
                                    {% endfor %}
                                  {% else %}
                                    <li>None</li>
                                  {% endif %}
                                </li>
                                <li>
                                  <a href="#">
                                    <i class="fa fa-user-o"></i>
                                    {{ post.writer }}</a>
                                </li>
                                <li>
                                  <i class="fa fa-calendar-o"></i>
                                  {{ post.created_at|date:"M d Y" }}</a>
                              </li>
                            </ul>
                          </div>
                          <div class="entry-content">
                            <p>{{ post.content|base64_to_image|striptags }}</p>
                          </div>
                          <div class="entry-share clearfix">
                            <div class="entry-button">
                              <a class="button arrow" href="{% url 'blog:detail' pk=post.pk %}">Read More<i class="fa fa-angle-right" aria-hidden="true"></i>
                              </a>
                            </div>
                            <div class="social list-style-none float-end">
                              <strong>Share :
                              </strong>
                              <ul>
                                <li>
                                  <a href="#">
                                    <i class="fa fa-facebook"></i>
                                  </a>
                                </li>
                                <li>
                                  <a href="#">
                                    <i class="fa fa-twitter"></i>
                                  </a>
                                </li>
                                <li>
                                  <a href="#">
                                    <i class="fa fa-pinterest-p"></i>
                                  </a>
                                </li>
                                <li>
                                  <a href="#">
                                    <i class="fa fa-dribbble"></i>
                                  </a>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>
                  <!--================================= post without images -->
                {% else %}
                  <li class="timeline-inverted">
                    <div class="timeline-badge primary">
                      <a href="#">{{ post.created_at|date:"d" }}
                        <span>{{ post.created_at|date:"M" }}</span></a>
                    </div>
                    <div class="timeline-panel">
                      <div class="blog-entry">
                        <div class="blog-detail">
                          <div class="entry-title mb-10">
                            <a href="{% url 'blog:detail' pk=post.pk %}">{{ post.title }}</a>
                          </div>
                          <div class="entry-meta mb-10">
                            <ul>
                              <li>
                                <i class="fa fa-hashtag"></i>
                                {% if post.tags.all %}
                                  {% for tag in post.tags.all %}
                                    <li>
                                      <a href="" class='tagSearch'>
                                        {{ tag }}
                                      </a>
                                    </li>
                                  {% endfor %}
                                {% else %}
                                  <li>None</li>
                                {% endif %}
                              </li>
                              <li>
                                <a href="#">
                                  <i class="fa fa-user-o"></i>
                                  {{ post.writer }}</a>
                              </li>
                              <li>
                                <i class="fa fa-calendar-o"></i>
                                {{ post.created_at|date:"M d Y" }}</a>
                            </li>
                          </ul>
                        </div>
                        <div class="entry-content">
                          <p>{{ post.content|striptags }}</p>
                        </div>
                        <div class="entry-share clearfix">
                          <div class="entry-button">
                            <a class="button arrow" href="{% url 'blog:detail' pk=post.pk %}">Read More<i class="fa fa-angle-right" aria-hidden="true"></i>
                            </a>
                          </div>
                          <div class="social list-style-none float-end">
                            <strong>Share :
                            </strong>
                            <ul>
                              <li>
                                <a href="#">
                                  <i class="fa fa-facebook"></i>
                                </a>
                              </li>
                              <li>
                                <a href="#">
                                  <i class="fa fa-twitter"></i>
                                </a>
                              </li>
                              <li>
                                <a href="#">
                                  <i class="fa fa-pinterest-p"></i>
                                </a>
                              </li>
                              <li>
                                <a href="#">
                                  <i class="fa fa-dribbble"></i>
                                </a>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
              {% endif %}
            {% endif %}
          {% endfor %}
          <!-- =========================================== -->
          <li class="entry-date-bottom">
            <a href="#">Load more...</a>
          </li>
          <!-- =========================================== -->
          <li class="clearfix timeline-inverted" style="float: none;"></li>
        </ul>
      {% endif %}
    </div>
    <!-- ================================= -->
    <div class="col-lg-3 sm-mt-50">
      <div class="sidebar-widget">
        <h6 class="mt-40 mb-20">Post Write
        </h6>
        <a class="mb-20 py-3 button write" href="{% url 'blog:write' %}">Write</a>
      </div>
      <div class="sidebar-widget">
        <h6 class="mt-40 mb-20">Recent Comments
        </h6>
        {% if comments %}
          {% for comment in comments %}
            <div class="recent-post clearfix">
              <div class="recent-post-info">
                <a href="{% url 'blog:detail' pk=comment.post.id %}">{{ comment.content }}
                  -
                  {{ comment.writer }}</a>
                <span>
                  <i class="fa fa-calendar-o"></i>
                  {{ comment.created_at|date:"F d Y" }}</span>
              </div>
            </div>
          {% endfor %}
        {% endif %}
      </div>
      <div class="sidebar-widget">
        <h6 class="mt-40 mb-20">Tags</h6>
        <div class="widget-tags">
          <ul>
            {% if tags %}
              {% for tag in tags %}
                <li>
                  <a href="" class='tagSearch'>
                    {{ tag }}
                  </a>
                </li>
              {% endfor %}
            {% endif %}
          </ul>
        </div>
      </div>
      <div class="sidebar-widget">
        <h6 class="mt-40 mb-20">Youtube video</h6>
        <div class="js-video [youtube, widescreen]">
          <iframe src="https://www.youtube.com/embed/kKsivrgoyDw?autoplay=1&mute=1" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
        </div>
      </div>

      <div class="sidebar-widget">
        <h6 class="mt-40 mb-20">Quick contact</h6>
        <form class="gray-form">
          <div class="mb-3">
            <input type="email" class="form-control" placeholder="Name">
          </div>
          <div class="mb-3">
            <input type="email" class="form-control" id="exampleInputphone" placeholder="Email">
          </div>

          <div class="mb-3">
            <textarea class="form-control" rows="4" placeholder="message"></textarea>
          </div>
          <a class="button" href="#">Submit</a>
        </form>
      </div>
    </div>
  </div>
</div>
</section>

<!--================================= blog timeline sidebar-->
{% endblock %}

{% block extra_js %}
<script>
$tags = document.querySelectorAll('.tagSearch');
$tags.forEach((tag) => {
  tag.addEventListener('click', (event) => tagSearch(event, tag));
});

function tagSearch(event, tag) {
  event.preventDefault()
  const url = "{% url 'blog:tag-search' %}?name=" + tag
    .textContent
    .trim()
  window.location.href = url;
}
</script>
{% endblock %}